# fly.toml app configuration file generated for dark-frog-8016 on 2023-05-10T23:59:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-frog-8016"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"
processes = []

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.15.1"

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.script_checks]]
    command = "/app/health_check.sh"
    args = []
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "1s"